# Use the official MySQL image from Docker Hub
FROM mysql:8.4.0

# Set MySQL environment variables (change these as needed)
ENV MYSQL_ROOT_PASSWORD=elit_2000
ENV MYSQL_DATABASE=elit_cars
ENV MYSQL_USER=elit
ENV MYSQL_PASSWORD=elit_2000

# Expose MySQL port
EXPOSE 3306
